default_platform(:ios)

platform :ios do
  lane :staging do |options|
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    match(type: "appstore")
    build_app(scheme: "Release(stag)")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
  
  lane :production do |options|
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    match(type: "appstore")
    build_app(scheme: "Release(prod)")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
